"""
main.py

The entry point that ties the whole project together. Run this one file and it
takes the project from a raw CSV to a finished report without any further
input.

    python main.py

In order, it:

    1. loads data/city_day.csv, building it first if it is not there yet
    2. cleans the data and adds the derived columns (src/preprocessing.py)
    3. works out the summary statistics and the insights (src/eda_analysis.py)
    4. draws every chart into outputs/plots/ (src/visualizations.py)
    5. assembles the lot into outputs/EDA_Report.md

The notebook under notebooks/ walks through the same analysis step by step with
the charts inline, which is the better way to actually read it. This script is
for when you just want the artifacts regenerated.
"""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.data_loader import load_data, DEFAULT_DATA_PATH, POLLUTANT_COLUMNS
from src.preprocessing import clean_pipeline, missing_value_report
from src import eda_analysis as eda
from src import visualizations as viz

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT / "outputs"
PLOTS_DIR = OUTPUT_DIR / "plots"

DATA_CAVEAT = (
    "> **A note on the data.** `data/city_day.csv` is generated by "
    "`src/generate_dataset.py`, not downloaded from a monitoring network. It "
    "carries the same columns and the same shape as the Kaggle *Air Quality "
    "Data in India* dataset, and the seasonal, regional and lockdown patterns "
    "in it are modelled on the real ones, but the numbers below are not "
    "measurements of anything. The analysis is what this project is "
    "demonstrating; drop a real extract with the same column names into "
    "`data/` and every figure here recomputes against it."
)


def ensure_dataset():
    """Build the dataset if this is a fresh clone and it has not been made yet."""
    if not DEFAULT_DATA_PATH.exists():
        print("No dataset found, generating it first...")
        from src.generate_dataset import main as generate_main

        generate_main()


def run_visualizations(raw_df, clean_df):
    """Draw every chart and return the paths they were written to.

    The missing values chart is the one that has to run against the raw
    dataframe rather than the cleaned one, for the obvious reason that after
    cleaning there is nothing left to plot.
    """
    print("\nRendering charts...")
    paths = [
        viz.plot_missing_values(missing_value_report(raw_df), PLOTS_DIR),
        viz.plot_pollutant_distributions(clean_df, POLLUTANT_COLUMNS, PLOTS_DIR),
        viz.plot_correlation_heatmap(clean_df, POLLUTANT_COLUMNS + ["AQI"], PLOTS_DIR),
        viz.plot_city_avg_pm25(clean_df, PLOTS_DIR),
        viz.plot_monthly_trend(clean_df, PLOTS_DIR),
        viz.plot_yearly_trend(clean_df, PLOTS_DIR),
        viz.plot_daily_timeseries(clean_df, "Delhi", PLOTS_DIR),
        viz.plot_aqi_bucket_distribution(clean_df, PLOTS_DIR),
        viz.plot_city_boxplot(clean_df, PLOTS_DIR),
        viz.plot_weekday_effect(clean_df, PLOTS_DIR),
        viz.plot_region_comparison(clean_df, PLOTS_DIR),
    ]
    for path in paths:
        print(f"  saved -> {path.relative_to(PROJECT_ROOT)}")
    return paths


def build_report(raw_df, clean_df) -> str:
    """Assemble the Markdown report out of the tables, charts and insights."""
    stats = eda.descriptive_stats(clean_df)
    ranking = eda.city_ranking(clean_df)
    season = eda.seasonal_summary(clean_df)
    yearly = eda.yearly_summary(clean_df)
    corr = eda.correlation_with_aqi(clean_df)
    buckets = eda.aqi_bucket_share(clean_df)
    covid = eda.covid_impact(clean_df)
    outliers = eda.outlier_summary(clean_df)
    insights = eda.generate_text_insights(clean_df)
    missing = missing_value_report(raw_df)

    out = []
    add = out.append

    add("# Exploratory Data Analysis: Indian Air Quality Data\n")
    add(
        f"**Records analyzed:** {len(clean_df):,}  |  "
        f"**Cities:** {clean_df['City'].nunique()}  |  "
        f"**Date range:** {clean_df['Date'].min().date()} to "
        f"{clean_df['Date'].max().date()}\n"
    )
    add(DATA_CAVEAT + "\n")
    add(
        "This file is written by `main.py`. Every number and chart in it is "
        "regenerated from scratch on each run, so nothing here can drift out "
        "of step with the code that produced it.\n"
    )

    add("## 1. Data quality: what was missing before cleaning\n")
    add(missing.to_markdown())
    add("\n![Missing Values](plots/01_missing_values.png)\n")
    add(
        "Every pollutant column has gaps in it, running from roughly 2% up to "
        "8%. That is normal for this kind of data. Monitoring stations lose "
        "power, go down for maintenance, or fail validation checks, and the "
        "reading for that day simply never arrives.\n"
    )
    add(
        "The gaps are filled by `interpolate_by_city` in "
        "`src/preprocessing.py`, which interpolates against the date index one "
        "city at a time. Doing it per city is the part that matters: "
        "interpolating across the whole table at once would let a missing "
        "Delhi winter reading be filled with something shaped by Chennai's "
        "summer, which would be meaningless.\n"
    )

    add("## 2. Descriptive statistics after cleaning\n")
    add(stats.to_markdown())
    add("\n![Pollutant Distributions](plots/02_pollutant_distributions.png)\n")
    add(
        "Every pollutant is right skewed, with the mean sitting well above the "
        "median. That is the signature of a variable where most days are "
        "unremarkable and a handful are severe, and it is the reason the city "
        "ranking below reports the median alongside the mean.\n"
    )

    add("## 3. How each pollutant tracks the AQI\n")
    add(corr.to_frame(name="correlation_with_AQI").to_markdown())
    add("\n![Correlation Heatmap](plots/03_correlation_heatmap.png)\n")
    add(
        f"{corr.index[0]} leads at r = {corr.iloc[0]}. All the pollutants "
        "correlate positively with each other, which makes sense given they "
        "largely share sources and share the weather that either disperses or "
        "traps them.\n"
    )

    add("## 4. City ranking by mean PM2.5\n")
    add(ranking.to_markdown())
    add("\n![City Average PM2.5](plots/04_city_avg_pm25.png)\n")
    add("![City Boxplot](plots/09_city_boxplot.png)\n")
    add("![Region Comparison](plots/11_region_comparison.png)\n")
    add(
        "The split is regional rather than about city size. The four worst are "
        "all inland north Indian cities, and the cleanest are coastal or "
        "southern. Note the standard deviation column: the northern cities are "
        "not merely worse on average, they swing far harder between their good "
        "days and their bad ones.\n"
    )

    add("## 5. Seasonal and yearly trends\n")
    add("### Average PM2.5 by season\n")
    add(season.to_markdown())
    add("\n![Seasonal Trend](plots/05_seasonal_pm25_trend.png)\n")
    add("### Average PM2.5 by year\n")
    add(yearly.to_markdown())
    add("\n![Yearly Trend](plots/06_yearly_trend.png)\n")
    add("![Delhi Daily Timeseries](plots/07_daily_timeseries_delhi.png)\n")
    add("![Weekday NO2 Effect](plots/10_weekday_no2_effect.png)\n")
    add(
        "Season dominates. Winter runs at roughly "
        f"{round(season.iloc[0, 0] / season.iloc[-1, 0], 1)}x the "
        f"{season.index[-1].lower()} average, a bigger swing than the gap "
        "between the best and worst cities. The weekday chart is a much "
        "smaller effect, but the weekend dip in NO2 is visible and consistent, "
        "which is what you would expect from a pollutant driven by commuter "
        "traffic.\n"
    )

    add("## 6. AQI category breakdown\n")
    add(buckets.to_frame(name="% of days").to_markdown())
    add("\n![AQI Bucket Distribution](plots/08_aqi_bucket_distribution.png)\n")

    add("## 7. The COVID-19 lockdown, March to May 2020\n")
    add(
        f"- Same weeks in 2019, average PM2.5: **{covid['pre_lockdown_2019_avg']} µg/m³**"
    )
    add(f"- Lockdown period 2020, average PM2.5: **{covid['lockdown_2020_avg']} µg/m³**")
    add(f"- Change: **{covid['pct_change']}%**\n")
    add(
        "The comparison is against the same calendar weeks of the previous "
        "year rather than against the weeks immediately before lockdown. March "
        "to May is already falling away from the winter peak, so a "
        "before-and-after comparison inside 2020 would hand the lockdown "
        "credit for a seasonal decline that was coming regardless.\n"
    )

    add("## 8. Outliers\n")
    add(f"- Total records: {outliers['total_records']:,}")
    add(
        f"- Flagged as PM2.5 outliers (IQR, k = 1.5): "
        f"{outliers['outlier_records']:,} ({outliers['outlier_pct']}%)\n"
    )
    add(
        "These are flagged and kept, never dropped. On a right skewed seasonal "
        "variable the IQR test flags the entire northern winter, and those are "
        "the days the analysis most needs to keep. The flag is a column you "
        "can filter on, not a deletion.\n"
    )

    add("## 9. Key takeaways\n")
    for i, insight in enumerate(insights, 1):
        add(f"{i}. {insight}")

    return "\n".join(out) + "\n"


def main():
    ensure_dataset()

    print("Loading data...")
    raw_df = load_data()
    print(f"  {len(raw_df):,} rows, {raw_df['City'].nunique()} cities")

    print("Cleaning and adding derived columns...")
    clean_df = clean_pipeline(raw_df)
    print(f"  {len(clean_df):,} rows after cleaning")

    run_visualizations(raw_df, clean_df)

    print("\nComputing statistics and building the report...")
    report = build_report(raw_df, clean_df)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = OUTPUT_DIR / "EDA_Report.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"Report saved -> {report_path.relative_to(PROJECT_ROOT)}")

    # The cleaned dataset gets written out too, so anything built on top of
    # this later does not have to rerun the whole pipeline first.
    clean_csv_path = OUTPUT_DIR / "city_day_cleaned.csv"
    clean_df.to_csv(clean_csv_path, index=False)
    print(f"Cleaned dataset saved -> {clean_csv_path.relative_to(PROJECT_ROOT)}")

    print("\nDone.")
    print("\n--- Key takeaways ---")
    for i, insight in enumerate(eda.generate_text_insights(clean_df), 1):
        print(f"{i}. {insight}")


if __name__ == "__main__":
    main()
